github actions: apply changes from main repo to packages.yml

diff --git a/.github/workflows/packages.yml b/.github/workflows/packages.yml
--- a/.github/workflows/packages.yml
+++ b/.github/workflows/packages.yml
@@ -1,12 +1,12 @@
 name: Packages
 
 on:
-  pull_request:
-    paths:
-    - 'packages/**'
   push:
     branches:
     - master
+    paths:
+    - 'packages/**'
+  pull_request:
     paths:
     - 'packages/**'
 
@@ -19,17 +19,12 @@ jobs:
     strategy:
       matrix:
         target_arch: [aarch64, arm, i686, x86_64]
+      fail-fast: false
     steps:
     - name: Clone repository
       uses: actions/checkout@v2
       with:
         fetch-depth: 1000
-    - name: Free additional disk space on host
-      run: |
-        sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php)') \
-          liblldb-6.0 libllvm6.0:amd64 mono-runtime-common monodoc-manual ruby
-        sudo apt autoremove -yq
-        sudo rm -rf /usr/local
     - name: Build packages
       run: |
         BASE_COMMIT=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH")
@@ -51,12 +46,12 @@ jobs:
           echo "Processing pull request #$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH"): ${BASE_COMMIT}..HEAD"
           CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r "${BASE_COMMIT}" "HEAD")
         fi
-        mkdir -p ./artifacts ./debs
-        touch ./debs/.placeholder
+        mkdir -p ./artifacts ./output
+        touch ./output/.placeholder
         # Process tag '%ci:no-build' that may be added as line to commit message.
         # Forces CI to cancel current build with status 'passed'.
         if grep -qiP '^\s*%ci:no-build\s*$' <(git log --format="%B" -n 1 "HEAD"); then
-          tar cf artifacts/debs-${{ matrix.target_arch }}.tar debs
+          tar cf artifacts/output-${{ matrix.target_arch }}.tar output
           echo "[!] Force exiting as tag '%ci:no-build' was applied to HEAD commit message."
           exit 0
         fi
@@ -105,25 +100,37 @@ jobs:
           mv ./deleted_packages.txt.tmp ./deleted_packages.txt
         fi
 
+        if grep -qP '^rust$' ./built_packages.txt ; then
+          echo "Free additional disk space on host"
+          sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php)') \
+            liblldb-6.0 libllvm6.0:amd64 mono-runtime-common monodoc-manual powershell ruby
+          sudo apt autoremove -yq
+          sudo rm -rf /opt/hostedtoolcache /usr/local /usr/share/dotnet /usr/share/swift
+        fi
+
         if [ -f ./built_packages.txt ]; then
           ./scripts/lint-packages.sh $(cat ./built_packages.txt | awk '{print "packages/"$1"/build.sh"}')
-          ./start-builder.sh ./build-package.sh -o ./debs -a ${{ matrix.target_arch }} -I $(cat ./built_packages.txt)
+          ./start-builder.sh ./build-package.sh -o ./output -I -a ${{ matrix.target_arch }} $(cat ./built_packages.txt)
         fi
 
         # Put package lists into directory with *.deb files so they will be transferred to
         # upload job.
-        test -f ./built_packages.txt && mv ./built_packages.txt ./debs/
-        test -f ./built_subpackages.txt && cat ./built_subpackages.txt >> ./debs/built_packages.txt \
+        test -f ./built_packages.txt && mv ./built_packages.txt ./output/
+        test -f ./built_subpackages.txt && cat ./built_subpackages.txt >> ./output/built_packages.txt \
           && rm ./built_subpackages.txt
-        test -f ./deleted_packages.txt && mv ./deleted_packages.txt ./debs/
+        test -f ./deleted_packages.txt && mv ./deleted_packages.txt ./output/
         # Files containing certain symbols (e.g. ":") will cause failure in actions/upload-artifact.
         # Archiving *.deb files in a tarball to avoid issues with uploading.
-        tar cf artifacts/debs-${{ matrix.target_arch }}-${{ github.sha }}.tar debs
+        tar cf artifacts/output-${{ matrix.target_arch }}-${{ github.sha }}.tar output
+    - name: Checksums for built *.deb files
+      run: |
+        find output -type f -name "*.deb" -exec sha256sum "{}" \; | sort -k2
     - name: Store *.deb files
       uses: actions/upload-artifact@v2
       with:
-        name: unstable-packages-${{ github.sha }}
+        name: unstable-packages-${{ matrix.target_arch }}-${{ github.sha }}
         path: ./artifacts
+
   upload:
     if: github.event_name != 'pull_request'
     needs: build
@@ -134,14 +141,13 @@ jobs:
     - name: Get *.deb files
       uses: actions/download-artifact@v2
       with:
-        name: unstable-packages-${{ github.sha }}
         path: ./
     - name: Upload to packages.termux.org
       env:
         REPOSITORY_NAME: termux-unstable
         REPOSITORY_DISTRIBUTION: unstable
       run: |
-        for archive in *.tar; do
+        for archive in unstable-packages-*/*.tar; do
           tar xf "$archive"
         done
 
@@ -169,7 +175,7 @@ jobs:
         # Upload file to temporary directory.
         uploaded_files=false
         shopt -s nullglob
-        for filename in $(cat debs/built_packages.txt | sed -E 's/(..*)/debs\/\1_\*.deb debs\/\1-static_\*.deb/g'); do
+        for filename in $(cat output/built_packages.txt | sed -E 's/(..*)/output\/\1_\*.deb output\/\1-static_\*.deb/g'); do
           curl_response=$(
             curl \
               --silent \
@@ -207,7 +213,7 @@ jobs:
               --user "${{ secrets.APTLY_API_AUTH }}" \
               --request POST \
               --write-out "|%{http_code}" \
-              https://packages.termux.org/aptly-api/repos/${REPOSITORY_NAME}/file/${REPOSITORY_NAME}-${{ github.sha }}
+              https://packages.termux.org/aptly-api/repos/${REPOSITORY_NAME}/file/${REPOSITORY_NAME}-${{ github.sha }} || true
           )
 
           http_status_code=$(echo "$curl_response" | cut -d'|' -f2)
@@ -220,39 +226,30 @@ jobs:
               echo "$warnings"
               echo
             fi
-
-            # Upload directory is usually deleted automatically once all deb
-            # files were added without issues. Attempting to do this manually
-            # in case it left for some reason (e.g. some debs not added due to
-            # conflicts).
-            aptly_delete_dir
-          else
-            echo "[*] Server returned $http_status_code. Not publishing repository!"
-            aptly_delete_dir
-            exit 1
           fi
+          # Usually temporary directory is deleted automatically, but in certain cases it is left.
+          aptly_delete_dir
 
           # Final part to make changes appear in web root.
           echo "[*] Publishing repository changes..."
+          set +e
+          curl \
+            --silent \
+            --user "${{ secrets.APTLY_API_AUTH }}" \
+            --header 'Content-Type: application/json' \
+            --request PUT \
+            --data '{"Signing": {"Passphrase": "${{ secrets.GPG_PASSPHRASE }}"}}' \
+            https://packages.termux.org/aptly-api/publish/${REPOSITORY_NAME}/${REPOSITORY_DISTRIBUTION}
+          exit_code=$?
+          echo
 
-          curl_response=$(
-            curl \
-              --silent \
-              --user "${{ secrets.APTLY_API_AUTH }}" \
-              --header 'Content-Type: application/json' \
-              --request PUT \
-              --data '{"Signing": {"Passphrase": "${{ secrets.GPG_PASSPHRASE }}"}}' \
-              --write-out "|%{http_code}" \
-              https://packages.termux.org/aptly-api/publish/${REPOSITORY_NAME}/${REPOSITORY_DISTRIBUTION}
-          )
-
-          http_status_code=$(echo "$curl_response" | cut -d'|' -f2)
-
-          if [ "$http_status_code" = "200" ]; then
+          if [ "$exit_code" = 0 ]; then
             echo "[*] Repository updated successfully."
+          elif [ "$exit_code" = 52 ]; then
+            echo "[!] Repository update takes more time than expected, server returned empty response."
+            echo "[!] This is expected if large amount of data has been submitted."
           else
-            # Note: may return error 500 if gpg signing failed.
-            echo "[*] Server returned $http_status_code."
-            exit 1
+            echo "[!] curl exited with error code $exit_status."
+            exit "$exit_code"
           fi
         fi
